* Code Zauker: your code, indexed
Code Zauker is a search engine for programming languages.
Code Zauker is based from ideas taken by old Google Code Search and uses Redis as a basic platform

For news and discussion: http://gioorgi.com/tag/code-zauker/


* INSTALL
To install Code Zauker,simply issue
#+BEGIN_SRC sh
  gem install code_zauker
#+END_SRC
You need also [[http://redis.io/][redis-2.4.6]] or better. 
For a sample redis configuration see the etc/ directory of the project


* Release History
  | Version | Date        | Summary                                              |
  |---------+-------------+------------------------------------------------------|
  |   0.0.5 |             | Added web search page and SQLite experimental plugin |
  |   0.0.4 | 12 Feb 2012 | PDF Searching                                        |
  |   0.0.3 | 03 Feb 2012 | Added Case insensitive search.UTF-8 trigram database |
  |   0.0.2 | 29 Jan 2012 | Removed dependency on unix find for czindexer.       |
  |   0.0.1 | 26 Jan 2012 | First RubyGems Release (for testing purpose only)    |
  |         |             |                                                      |
  |         |             |                                                      |


* SQL Lite plugin
The sqlite plugin is an experimental branch for replacing redis with a api-compatibility layer based on sql-lite.
This plugin aims to provide 
1. an embedded solution
2. a less resource hangry implementation, particular on RAM requirements.

Major disavantages:
1. Redis compress data file. SQLite doesn't.
Resulting data will be very huge
2. SQLite performance seems to degrade on a huge database


First relase is quite fast when working only on memory, and can get good performance on file system too:
#+BEGIN_SRC sh
time bin/czindexer -S :memory: -f  /k/code/code_zauker/
End:48 files Files per sec:2.153639026673998

real    0m24.551s
user    0m21.065s
sys     0m1.692s

#+END_SRC




* DEVELOPING
For developing with Code Zauker you need bundler 1.0.21 or above
See devel.org file

